### ISSUE TITLE
Error while generating models

### ISSUE THREAD

**Issue by kazitanvirahsan** [lukebaker/activerecord-php#2]
I like the idea behind this project. However, when I try to run this project I encountered the following issue

PHP Fatal error:  Declaration of MySQLAdapter::get_dbh($host = 'localhost', $db = NULL, $user = NULL, $password = NULL, $driver = 'mysql') must be compatible with DatabaseAdapter::get_dbh($host = 'localhost', $port = '3306', $db = NULL, $user = NULL, $password = NULL, $driver = 'mysql') in /var/www/html/activerecord-php/activerecord-php/db_adapters/MySQL.php on line 3

While looking into the code, I see DatabaseAdapter is defined in ActiveRecord.php with different function parameters. 

Probably, the project is not maintained anymore.

**Comment by lukebaker** [comment]
Yes, this project is no longer maintained. There are better ORMs for PHP these days.
